name: Update Table of Contents

on:
  push:
    branches:
      - auto_gen_toc
  pull_request:
    branches:
      - auto_gen_toc
jobs:
  update_table_of_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate Table of Contents
        run: |
          node generate_toc.js
