name: Update Table of Contents (Branch 2)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_table_of_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate Table of Contents
        run: |
          node generate_toc.js
